In [ ]:
!conda install opencv


Solving environment: done

## Package Plan ##

  environment location: /Users/sankettangade/anaconda3

  added / updated specs:
    - opencv


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    boltons-23.0.0             |  py310hecd8cb5_0         426 KB
    cairo-1.16.0               |       h3ce6f7e_4        1011 KB
    conda-23.3.1               |  py310hecd8cb5_0         973 KB
    eigen-3.3.7                |       haf03e11_1         832 KB
    expat-2.4.9                |       he9d5cce_0         127 KB
    ffmpeg-4.2.2               |       h97e5cf8_0        22.9 MB
    fontconfig-2.14.1          |       hedf32ac_1         249 KB
    gnutls-3.6.15              |       hed9c0bf_0         974 KB
    graphite2-1.3.14           |       he9d5cce_1          82 KB
    harfbuzz-4.3.0             |       hffc734d_1         1.2 MB
    jsonpatch-1.32             |     pyhd3eb1b0_0          15 K

In [33]:
import os
import cv2
import numpy as np

class_names = sorted(os.listdir("train"))

In [34]:
class_names

['AFRICAN LEOPARD',
 'CARACAL',
 'CHEETAH',
 'CLOUDED LEOPARD',
 'JAGUAR',
 'LIONS',
 'OCELOT',
 'PUMA',
 'SNOW LEOPARD',
 'TIGER']

In [35]:
x_train = []
y_train = []

for i, class_name in enumerate(class_names):
    class_dir = os.path.join("train", class_name)
    for filename in os.listdir(class_dir):
        # Load the image and convert it to a numpy array
        img = cv2.imread(os.path.join(class_dir, filename))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img_array = np.array(img)

        # Append the numpy array to x_train
        x_train.append(img_array)

        # Append the corresponding label to y_train
        y_train.append(i)

# Convert x_train and y_train to numpy arrays
x_train = np.array(x_train)
y_train = np.array(y_train)

In [36]:
from tensorflow.keras.utils import to_categorical

y_train = to_categorical(y_train, num_classes=10)

In [37]:
class_map = {i: class_names[i] for i in range(len(class_names))}

In [38]:
y_train

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [39]:
x_val = []
y_val = []

for i, class_name in enumerate(class_names):
    class_dir = os.path.join("valid", class_name)
    for filename in os.listdir(class_dir):
        # Load the image and convert it to a numpy array
        img = cv2.imread(os.path.join(class_dir, filename))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img_array = np.array(img)

        # Append the numpy array to x_train
        x_val.append(img_array)

        # Append the corresponding label to y_train
        y_val.append(i)

# Convert x_train and y_train to numpy arrays
x_val = np.array(x_val)
y_val = np.array(y_val)

In [40]:
y_val = to_categorical(y_val, num_classes=10)
print(y_val)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0.

In [41]:
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit

# Concatenate the x and y arrays
x_all = np.concatenate([x_train, x_val], axis=0)
y_all = np.concatenate([y_train, y_val], axis=0)

# Create a StratifiedShuffleSplit object
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

# Use the StratifiedShuffleSplit object to split the data
train_indices, test_indices = next(sss.split(x_all, y_all))

# Split the data into training and testing sets
x_train_new, x_test_new = x_all[train_indices], x_all[test_indices]
y_train_new, y_test_new = y_all[train_indices], y_all[test_indices]

# Verify the shapes of the new arrays
print(f'Shape of x_train_new: {x_train_new.shape}')
print(f'Shape of y_train_new: {y_train_new.shape}')
print(f'Shape of x_test_new: {x_test_new.shape}')
print(f'Shape of y_test_new: {y_test_new.shape}')


Shape of x_train_new: (1911, 224, 224, 3)
Shape of y_train_new: (1911, 10)
Shape of x_test_new: (478, 224, 224, 3)
Shape of y_test_new: (478, 10)


In [47]:
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Input, Flatten, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

# Load the pre-trained ResNet50 model
resnet_model = ResNet50(weights='imagenet', include_top=False, input_tensor=Input(shape=(224, 224, 3)))

# Freeze the layers in the pre-trained model
for layer in resnet_model.layers:
    layer.trainable = False

# Add your own classification layers
x = Flatten()(resnet_model.output)
x = Dense(512, activation='relu')(x)
x = Dense(256, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)

# Create the new model
model = Model(inputs=resnet_model.input, outputs=predictions)

# Compile the model with a lower learning rate
opt = Adam(learning_rate=0.001)
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

# Fit the model with validation data
history = model.fit(x_train_new, y_train_new, epochs=6, batch_size=32, validation_data=(x_test_new, y_test_new))

# Save the model
model.save("Models/resnet50.h5")


Epoch 1/6
60/60 [==============================] - 297s 5s/step - loss: 12.3146 - accuracy: 0.6154 - val_loss: 2.3101 - val_accuracy: 0.7615
Epoch 2/6
60/60 [==============================] - 313s 5s/step - loss: 0.5451 - accuracy: 0.9278 - val_loss: 1.2948 - val_accuracy: 0.8494
Epoch 3/6
60/60 [==============================] - 296s 5s/step - loss: 0.1663 - accuracy: 0.9702 - val_loss: 1.7123 - val_accuracy: 0.8347
Epoch 4/6
60/60 [==============================] - 329s 6s/step - loss: 0.2319 - accuracy: 0.9712 - val_loss: 1.4900 - val_accuracy: 0.8598
Epoch 5/6
60/60 [==============================] - 317s 5s/step - loss: 0.1161 - accuracy: 0.9796 - val_loss: 1.2487 - val_accuracy: 0.8891
Epoch 6/6
60/60 [==============================] - 311s 5s/step - loss: 0.0644 - accuracy: 0.9864 - val_loss: 1.6105 - val_accuracy: 0.8389


In [32]:
from tensorflow.keras.applications import Xception
from tensorflow.keras.layers import Input, Flatten, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Load the pre-trained Xception model
xception_model = Xception(weights='imagenet', include_top=False, input_tensor=Input(shape=(224, 224, 3)))

# Freeze the layers in the pre-trained model except the last few layers
for layer in xception_model.layers[:-10]:
    layer.trainable = False

# Add your own classification layers
x = Flatten()(xception_model.output)
x = Dense(512, activation='relu')(x)
x = Dense(256, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)

# Create the new model
model = Model(inputs=xception_model.input, outputs=predictions)

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Data augmentation
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

validation_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow(x_train_new, y_train_new, batch_size=32)
validation_generator = validation_datagen.flow(x_test_new, y_test_new, batch_size=32)

# Train the model
history = model.fit(
    train_generator,
    epochs=5,
    validation_data=validation_generator
)

# Save the model
model.save("Models/xception_finetuned.h5")


Epoch 1/5
60/60 [==============================] - 274s 5s/step - loss: 1.5057 - accuracy: 0.7368 - val_loss: 0.9537 - val_accuracy: 0.7615
Epoch 2/5
60/60 [==============================] - 291s 5s/step - loss: 0.4366 - accuracy: 0.8859 - val_loss: 0.2799 - val_accuracy: 0.9268
Epoch 3/5
60/60 [==============================] - 571s 10s/step - loss: 0.2924 - accuracy: 0.9063 - val_loss: 0.7651 - val_accuracy: 0.8556
Epoch 4/5
60/60 [==============================] - 288s 5s/step - loss: 0.3366 - accuracy: 0.9042 - val_loss: 0.2995 - val_accuracy: 0.9059
Epoch 5/5
60/60 [==============================] - 302s 5s/step - loss: 0.2597 - accuracy: 0.9267 - val_loss: 1.0770 - val_accuracy: 0.7573


In [ ]:
# import cv2
# import numpy as np

# # Apply image sharpening
# kernel = np.array([[-1,-1,-1], [-1,9,-1], [-1,-1,-1]]) # define a sharpening kernel
# sharpened_train = np.zeros_like(x_train) # create an empty array to store the sharpened images
# for i in range(x_train.shape[0]):
#     img = x_train[i]
#     sharpened = cv2.filter2D(img, -1, kernel)
#     sharpened_train[i] = sharpened

# # Apply histogram equalization
# equalized_train = np.zeros_like(sharpened_train) # create an empty array to store the equalized images
# for i in range(sharpened_train.shape[0]):
#     img = sharpened_train[i]
#     img_yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
#     img_yuv[:,:,0] = cv2.equalizeHist(img_yuv[:,:,0])
#     equalized = cv2.cvtColor(img_yuv, cv2.COLOR_YUV2BGR)
#     equalized_train[i] = equalized


In [51]:
import cv2
import numpy as np

# Define the sharpening kernel
kernel = np.array([[-1,-1,-1],[-1,9,-1],[-1,-1,-1]])

# Apply histogram equalization and sharpening to x_train_new
for i in range(len(x_train_new)):
    # Convert image to grayscale
    gray = cv2.cvtColor(x_train_new[i], cv2.COLOR_BGR2GRAY)
    
    # Apply histogram equalization
    equalized = cv2.equalizeHist(gray)
    
    # Apply sharpening
    sharpened = cv2.filter2D(equalized, -1, kernel)
    
    # Convert back to BGR color space
    x_train_new[i] = cv2.cvtColor(sharpened, cv2.COLOR_GRAY2BGR)

# Apply histogram equalization and sharpening to x_test_new
for i in range(len(x_test_new)):
    # Convert image to grayscale
    gray = cv2.cvtColor(x_test_new[i], cv2.COLOR_BGR2GRAY)
    
    # Apply histogram equalization
    equalized = cv2.equalizeHist(gray)
    
    # Apply sharpening
    sharpened = cv2.filter2D(equalized, -1, kernel)
    
    # Convert back to BGR color space
    x_test_new[i] = cv2.cvtColor(sharpened, cv2.COLOR_GRAY2BGR)


In [ ]:
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Input, Flatten, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

# Load the pre-trained ResNet50 model
resnet_model = ResNet50(weights='imagenet', include_top=False, input_tensor=Input(shape=(224, 224, 3)))

# Freeze the layers in the pre-trained model
for layer in resnet_model.layers:
    layer.trainable = False

# Add your own classification layers
x = Flatten()(resnet_model.output)
x = Dense(512, activation='relu')(x)
x = Dense(256, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)

# Create the new model
model = Model(inputs=resnet_model.input, outputs=predictions)

# Compile the model with a lower learning rate
opt = Adam(learning_rate=0.001)
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

# Fit the model with validation data
history = model.fit(x_train_new, y_train_new, epochs=6, batch_size=32, validation_data=(x_test_new, y_test_new))

# Save the model
model.save("Models/resnet50_tl.h5")


In [21]:
x_train[4]

array([[[172, 152,  81],
        [170, 154,  79],
        [168, 156,  80],
        ...,
        [133,  95,  46],
        [135,  94,  38],
        [165, 123,  63]],

       [[155, 140,  71],
        [171, 159,  87],
        [176, 170,  94],
        ...,
        [130,  92,  43],
        [142, 103,  44],
        [168, 128,  66]],

       [[148, 143,  77],
        [137, 134,  65],
        [134, 137,  66],
        ...,
        [131,  91,  40],
        [142, 106,  44],
        [160, 125,  59]],

       ...,

       [[173, 152,  97],
        [217, 198, 155],
        [156, 146, 121],
        ...,
        [ 70,  74,  57],
        [ 84,  88,  71],
        [ 67,  74,  56]],

       [[193, 165, 115],
        [221, 196, 155],
        [232, 211, 190],
        ...,
        [ 55,  58,  39],
        [ 67,  69,  48],
        [ 58,  60,  38]],

       [[207, 177, 127],
        [228, 200, 160],
        [243, 218, 198],
        ...,
        [ 62,  65,  46],
        [ 70,  69,  48],
        [ 68,  68,  44]]